apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask
spec:
  replicas: 2  # Uygulamanın kaç kopyası olacağını belirler
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: bbw0r1d/simple-flask:2.0  # İmaj adını buraya yaz
        ports:
        - containerPort: 5000


